name: xdnmb
description: An app for nmbxd.com.
publish_to: 'none'
version: 0.3.2-alpha+8

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: '>=3.10.1'

dependencies:
  align_positioned: ^3.0.0
  anchor_scroll_controller:
    git:
      url: https://github.com/orzogc/anchor_scroll_controller.git
      ref: xdnmb2
  cached_network_image: ^3.2.3
  crypto: ^3.0.3
  date_format: ^2.0.7
  device_info_plus: ^9.0.1
  easy_refresh: ^3.3.2+1
  expandable_text: ^2.3.0
  external_path: ^1.0.3
  file_picker: ^5.3.0
  float_column: 1.3.3
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_colorpicker: ^1.0.3
  flutter_easyloading: ^3.0.5
  flutter_expanded_tile: ^0.3.7
  flutter_keyboard_visibility: ^5.4.3
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  flutter_swipe_detector: ^2.0.0
  get: ^4.6.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html_to_text:
    git: https://github.com/orzogc/html_to_text.git
  http: ^0.13.6
  image_painter: ^0.5.0
  infinite_scroll_pagination: ^3.2.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  loader_overlay: ^2.2.0
  media_scanner: ^2.1.0
  mime: ^1.0.4
  mobile_scanner: ^3.2.0
  package_info_plus: ^4.0.1
  path: ^1.8.2
  path_provider: ^2.0.15
  permission_handler: ^10.2.0
  responsive_grid_list: ^1.3.2
  saver_gallery: ^2.0.1
  screenshot: ^2.1.0
  showcaseview: ^2.0.3
  swipeable_page_route: ^0.3.1
  system_info2: ^4.0.0
  timeago_flutter: ^3.4.0
  url_launcher: ^6.1.11
  uuid: ^3.0.7
  version: ^3.0.2
  xdg_directories: ^1.0.0
  xdnmb_api:
    git: https://github.com/orzogc/xdnmb_api.git

dev_dependencies:
  build_runner: ^2.4.4
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  assets:
    - LICENSE

    # https://letsencrypt.org/certs/lets-encrypt-r3.pem
    - assets/ca/lets-encrypt-r3.pem

    # Reward QR code
    - assets/image/reward_qrcode.png

  fonts:
    # Icon from https://www.fluttericon.com/
    - family: DiceIcon
      fonts:
        - asset: assets/fonts/DiceIcon.ttf
    - family: HeartIcon
      fonts:
        - asset: assets/fonts/HeartIcon.ttf

    # Noto font from Google
    #- family: 'Noto Sans'
    #  fonts:
    #    - asset: assets/fonts/NotoSans-Regular.ttf
    
    # Font from https://github.com/satbyy/go-noto-universal
    # with removing hangul.
    - family: 'Go Noto CJKCore'
      fonts:
        - asset: assets/fonts/GoNotoCJKCore.ttf

flutter_launcher_icons:
  image_path_android: assets/icons/icon.png
  image_path_ios: assets/icons/icon_ios.png
  android: true
  ios: true
  min_sdk_android: 21
  linux:
    generate: true
    image_path: assets/icons/icon.png
  macos:
    generate: true
    image_path: assets/icons/icon.png
  windows:
    generate: true
    image_path: assets/icons/icon.png
    icon_size: 48
