name: xdnmb
description: An app for nmbxd.com.

publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  align_positioned: ^3.0.0
  anchor_scroll_controller:
    git:
      url: https://github.com/orzogc/anchor_scroll_controller.git
      ref: fix
  cached_network_image: ^3.2.2
  date_format: ^2.0.7
  easy_refresh: ^3.0.4+2
  expandable_text: ^2.3.0
  external_path: ^1.0.3
  file_picker: ^5.2.1
  float_column: ^1.3.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_easyloading: ^3.0.5
  flutter_keyboard_visibility: ^5.4.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^6.0.0
  flutter_swipe_detector: ^2.0.0
  get: ^4.6.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html_to_text:
    git: https://github.com/orzogc/html_to_text.git
  http: ^0.13.5
  image_painter: ^0.4.6
  infinite_scroll_pagination: ^3.2.0
  isar: ^3.0.2
  isar_flutter_libs: ^3.0.2
  loader_overlay: ^2.1.0
  mime: ^1.0.2
  package_info_plus: ^2.0.0
  path: ^1.8.2
  path_provider: ^2.0.11
  permission_handler: ^10.1.0
  responsive_grid_list: ^1.3.0
  screenshot: ^1.2.3
  url_launcher: ^6.1.6
  uuid: ^3.0.6
  xdg_directories: ^0.2.0+2
  xdnmb_api:
    git: https://github.com/orzogc/xdnmb_api.git

dev_dependencies:
  build_runner: ^2.3.0
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  isar_generator: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/ca/lets-encrypt-r3.pem

  fonts:
    - family: DiceIcon
      fonts:
        - asset: assets/fonts/DiceIcon.ttf

flutter_icons:
  image_path_android: assets/icons/icon.png
  image_path_ios: assets/icons/icon_ios.png
  android: true
  ios: true
  min_sdk_android: 18
  linux:
    generate: true
    image_path: assets/icons/icon.png
  macos:
    generate: true
    image_path: assets/icons/icon.png
  windows:
    generate: true
    image_path: assets/icons/icon.png
    icon_size: 48
